AllCops:
  Include:
    - "terashiy_bot/**/*.rb"
  DisplayCopNames: true
Style/AsciiComments:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: trailing
Style/EmptyElse:
  EnforcedStyle: empty
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 20