AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  terashiy_bot

  Sample SAM Template for terashiy_bot

Globals:
  Function:
    Timeout: 3

Resources:
  BotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: terashiy_bot/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Timeout: 120
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref DDBTable
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(30 9 * * ? *)
  DDBTable:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5


